# Generated by Django 3.1.5 on 2021-01-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
