# Generated by Django 3.1.5 on 2021-04-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20210414_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
