# Generated by Django 3.1.5 on 2021-05-23 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_auto_20210523_2009'),
        ('qna', '0004_auto_20210507_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authuser.userprofile'),
        ),
    ]
