# Generated by Django 3.1.5 on 2021-01-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree_title',
            new_name='degree_name',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='university_name',
            new_name='school_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='visit_link',
            new_name='project_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='front_icon',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modules',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, choices=[('C', 'CGPA'), ('P', 'PERCENTILE'), ('G', 'GPA')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='card_color',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('indigo', 'INDIGO'), ('blue', 'BLUE'), ('light-blue', 'LIGHT BLUE'), ('cyan', 'CYAN'), ('tael', 'TEAL'), ('green', 'GREEN'), ('light-green', 'LIGHT GREEN'), ('yellow', 'YELLOW'), ('amber', 'AMBER'), ('orange', 'ORANGE'), ('deep-orange', 'DEEP ORANGE'), ('brown', 'BROWN'), ('grey', 'GREY'), ('blue-grey', 'BLUE GREY'), ('black', 'BLACK')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
